const LEGACY_GREETING_PROMPT = "分析当前岗位的职责、核心能力、专业词，并生成3条110-170字的中文 BOSS 首轮招呼语。每条招呼语要自然说明：我对哪些方向感兴趣、我做过哪些与岗位匹配的工作或项目、为什么想沟通。避免空泛套话。";
const DEFAULT_GREETING_PROMPT = `请先从岗位 JD 中提取 5-10 个最重要的能力点或经历要求，综合考虑出现频率、在 JD 中的位置，以及是否属于岗位职责和任职要求中的核心内容。然后选择与简历最相关的 1-2 个能力点，用 JD 原话或关键词自然表达，并用简历中的具体项目、工作内容、行动和结果证明匹配。简历没有明确证据的能力不得虚构；如果是岗位核心要求，可以用一句话表达学习意愿或对行业的关注。最终生成 3 条适合直接发送给招聘者的中文 BOSS 首轮招呼语，每条 150-200 个中文字符，使用 3 段排版：第一段说明岗位兴趣和匹配关键词，第二段用一段真实经历证明能力，第三段处理明显差距并表达希望进一步交流。每条消息只保留最相关的 1-2 个 JD 能力点，不要写成简历摘要、分析报告或正式求职信，不要使用项目符号、编号、小标题、Markdown 或空泛套话。`;
const buildGreetingPrompt = (writingRequirements, resumeContent, job) => `你是有招聘经验的 BOSS 直聘求职沟通助手。请站在招聘者视角，判断这份简历是否值得继续沟通。只能依据简历内容和岗位 JD，不得虚构经历、能力、数据或行业经验。\n\n你的任务分为两部分：\n\n一、岗位匹配分析（先分析，再写招呼语）\n1. 从 JD 中提取 5-10 个最重要的能力点、工作内容或经历要求。综合考虑出现频率、在 JD 中的位置，以及是否属于岗位职责和任职要求中的核心内容。\n2. 对每个能力点保留 JD 原话或关键词，并判断简历中是否有明确匹配证据。\n3. 选择最相关的 1-2 个核心能力点，必须用 JD 原话或关键词，并用简历中的具体项目、工作内容、行动和结果证明。\n4. 如果某项岗位核心要求在简历中没有明确体现，不得假装匹配；记录为不匹配，并决定是表达学习意愿、表达行业兴趣，还是不主动提及。\n\n二、生成招呼语\n1. 生成 3 条不同风格的中文 BOSS 首轮招呼语，每条 150-200 个中文字符。\n2. 每条消息使用 3 段排版，段落之间用两个换行符分隔，不使用项目符号、编号、小标题或 Markdown。\n3. 第一段说明对岗位具体方向或业务的兴趣，并自然嵌入 1-2 个 JD 核心关键词。\n4. 第二段只使用一个最有说服力的简历项目或工作经历，说明做过什么、采取了什么行动、取得了什么结果。\n5. 第三段仅在存在明显核心差距时，用一句话表达学习意愿或行业关注；最后表达希望和贵公司进一步交流。\n6. 招呼语要像认真看过 JD 的真人，不要像简历摘要、分析报告或正式求职信。不要堆砌能力点，不要连续罗列项目，不要使用“具备较强综合能力”“相信我能胜任”等空话，不要整段复制 JD。\n\n用户补充写作要求：\n${writingRequirements}\n\n简历内容（只作为事实依据，不要概括成候选人画像）：\n${resumeContent}\n\n岗位信息与 JD：\n${JSON.stringify(job)}\n\n仅返回 JSON，不要输出 JSON 以外的解释：\n{"jd_priorities":[{"point":"JD 能力点或经历要求","jd_evidence":"JD 原话","priority":"高/中/低","matched":true,"resume_evidence":"简历中的明确证据"}],"matching_points":[{"jd_quote":"最终使用的 JD 原话或关键词","resume_evidence":"对应的简历经历"}],"gaps":[{"requirement":"简历中没有明确体现的核心要求","handling":"学习意愿/行业兴趣/不提及"}],"greetings":[{"style":"直接匹配型","text":""},{"style":"项目证据型","text":""},{"style":"自然沟通型","text":""}]}`;
const buildBatchGreetingPrompt = (writingRequirements, resumeContent, job) => `你是有招聘经验的 BOSS 直聘求职沟通助手。请根据简历内容和岗位 JD，直接生成可以发送给招聘者的首轮招呼语。只能依据简历和 JD，不得虚构经历、能力、数据或行业经验。\n\n只做以下事情：\n1. 从 JD 中选择最相关的 1-2 个能力点或经历要求，优先使用 JD 原话或关键词。\n2. 用简历中的一个具体项目或工作经历证明匹配，写清楚做过什么、怎么做、结果如何。\n3. 如果存在明显差距，用一句话表达学习意愿或对行业的兴趣，最后表达希望和贵公司进一步交流。\n4. 生成 3 条不同风格的中文 BOSS 首轮招呼语，每条 150-200 个中文字符，使用三段排版，段落之间空一行。\n\n严禁输出岗位匹配分析、能力评分、优先级、JD重点列表、简历概括、候选人画像、差距分析、解释文字、Markdown、小标题、项目符号或编号。最终只返回 JSON，且只能使用以下结构：\n{"greetings":[{"style":"直接匹配型","text":""},{"style":"项目证据型","text":""},{"style":"自然沟通型","text":""}]}\n\n用户补充写作要求：\n${writingRequirements}\n\n简历内容：\n${resumeContent}\n\n岗位信息与 JD：\n${JSON.stringify(job)}`;
let config = {}; let currentJob = null; let uploadedImages = []; let jobPromptOverride = "";
const $ = id => document.getElementById(id);
const send = message => new Promise((resolve, reject) => chrome.runtime.sendMessage(message, response => { const error = chrome.runtime.lastError; if (error) reject(new Error(error.message)); else resolve(response); }));
async function activeTab() {
  // Side Panel 获得焦点时，currentWindow 在少数 Chrome 版本中会返回扩展页而非网页标签。
  // 先取最后活跃窗口的当前标签；若仍不是 BOSS，则在当前浏览器窗口中寻找最近的 BOSS 职位页。
  const [focused] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  if (focused && /(^|\.)zhipin\.com$/.test(new URL(focused.url || "https://invalid.local").hostname)) return focused;
  const candidates = await chrome.tabs.query({ url: ["*://*.zhipin.com/job_detail/*", "*://*.zhipin.com/web/geek/jobs*"] });
  return candidates.sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0))[0] || focused;
}
function toast(message) { const el = $("toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 4200); }
function escapeHtml(value) { const el = document.createElement("div"); el.textContent = value || ""; return el.innerHTML; }
function setupConfig() { $("endpoint").value = config.endpoint || ""; $("model").value = config.model || ""; $("apiKey").value = config.apiKey || ""; $("candidateProfile").value = config.candidateProfile || ""; $("greetingPrompt").value = config.greetingPrompt || DEFAULT_GREETING_PROMPT; $("sendResume").checked = config.sendResume !== false; }
async function persistConfig(show = true) { config = { ...config, endpoint: $("endpoint").value.trim(), model: $("model").value.trim(), apiKey: $("apiKey").value.trim(), candidateProfile: $("candidateProfile").value.trim(), greetingPrompt: $("greetingPrompt").value.trim() || DEFAULT_GREETING_PROMPT, resumeImages: uploadedImages, sendResume: $("sendResume").checked }; await chrome.storage.local.set({ config }); if (show) toast("设置已保存"); }
async function allowApiOrigin() { const value = $("endpoint").value.trim(); if (!value) throw new Error("请先填写 AI API 地址。"); const origin = new URL(value).origin + "/*"; const ok = await chrome.permissions.request({ origins: [origin] }); if (!ok) throw new Error("需要允许访问该 AI 服务，才能继续。"); }
async function ai(messages, maxTokens, jsonMode = false) { await persistConfig(false); if (!config.apiKey) throw new Error("请先在设置中填写 AI API Key。"); const response = await send({ type: "AI_CALL", payload: { config, messages, maxTokens, jsonMode } }); if (!response?.ok) throw new Error(response?.error || "AI 请求失败"); return response.text; }
async function parseAiJson(text) { const response = await send({ type: "PARSE_JSON", text }); if (!response?.ok) { const rawText = String(text || ""); const preview = rawText.replace(/\s+/g, " ").slice(0, 120); const error = new Error(`${response?.error || "AI 返回格式异常，请确认模型支持文本对话后重试。"}${preview ? ` 返回片段：${preview}` : ""}`); error.rawResponse = rawText.slice(0, 20000); throw error; } return response.data; }
async function messagePage(tab, message) { try { return await chrome.tabs.sendMessage(tab.id, message); } catch (error) { if (!/Receiving end does not exist/i.test(error.message || "")) throw error; await chrome.scripting.executeScript({ target: { tabId: tab.id }, files: ["content.js"] }); return chrome.tabs.sendMessage(tab.id, message); } }
async function extractJob() { const tab = await activeTab(); const url = new URL(tab?.url || "https://invalid.local"); if (!/(^|\.)zhipin\.com$/.test(url.hostname)) throw new Error("未找到 BOSS 职位页。请打开职位详情或职位列表后，再点分析。"); const response = await messagePage(tab, { type: "EXTRACT_JOB" }); if (!response?.ok) throw new Error(response?.error || "页面读取失败"); return response.job; }
function renderJob(job) { $("jobTitle").textContent = job.title; $("jobMeta").textContent = [job.company, job.location, job.salary, job.communicationState].filter(Boolean).join(" · "); $("jobBadge").textContent = job.pageType; }
function renderAnalysis(data) { const greetings = Array.isArray(data.greetings) ? data.greetings : []; $("greeting").value = greetings[0]?.text || data.greeting || ""; $("jobGreetingPrompt").value = jobPromptOverride || config.greetingPrompt || DEFAULT_GREETING_PROMPT; const priorities = Array.isArray(data.jd_priorities) ? data.jd_priorities : []; const matches = Array.isArray(data.matching_points) ? data.matching_points : []; const gaps = Array.isArray(data.gaps) ? data.gaps : []; $("matchAnalysisContent").innerHTML = `<h4>JD 重点能力</h4>${priorities.length ? `<ol>${priorities.map(item => `<li><b>${escapeHtml(item.point || "未命名能力")}</b>（${escapeHtml(item.priority || "未标注") }）<br><span>JD 原话：${escapeHtml(item.jd_evidence || "未提供")}</span><br><span>简历证据：${escapeHtml(item.resume_evidence || (item.matched ? "已匹配，但未返回证据" : "未找到明确证据"))}</span></li>`).join("")}</ol>` : `<p class="hint">本次没有返回可展示的 JD 能力分析。</p>`}<h4>核心匹配</h4>${matches.length ? `<ul>${matches.map(item => `<li><b>${escapeHtml(item.jd_quote || "未提供 JD 关键词")}</b><br><span>${escapeHtml(item.resume_evidence || "未提供简历证据")}</span></li>`).join("")}</ul>` : `<p class="hint">本次没有返回明确的核心匹配项。</p>`}<h4>待补足项</h4>${gaps.length ? `<ul>${gaps.map(item => `<li><b>${escapeHtml(item.requirement || "未命名要求")}</b><br><span>${escapeHtml(item.handling || item.explanation || "未提供处理建议")}</span></li>`).join("")}</ul>` : `<p class="hint">暂未发现需要特别说明的核心缺口。</p>`}`; $("matchAnalysis").classList.toggle("hidden", !(priorities.length || matches.length || gaps.length)); $("result").classList.remove("hidden"); }
function renderSavedResumes() { const target = $("savedResumes"); target.innerHTML = uploadedImages.length ? uploadedImages.map((image, index) => `<div class="resume-file"><span>▣</span><span>${escapeHtml(image.name || `简历图片 ${index + 1}`)}</span><small>已保存</small></div>`).join("") : `<p class="hint">暂未保存简历图片。</p>`; }
async function analyze() { try { const promptField = $("jobGreetingPrompt"); if (promptField?.value.trim()) jobPromptOverride = promptField.value.trim(); $("analyze").disabled = true; $("analyze").textContent = "正在读取并分析…"; currentJob = await extractJob(); renderJob(currentJob); if (!config.candidateProfile) throw new Error("请先在设置中粘贴或解析简历内容。"); const prompt = buildGreetingPrompt(jobPromptOverride || config.greetingPrompt || DEFAULT_GREETING_PROMPT, config.candidateProfile, currentJob); const result = await parseAiJson(await ai([{ role: "user", content: prompt }], 2600, true)); renderAnalysis(result); toast("已完成 JD 与简历匹配，生成招呼语"); } catch (error) { toast(error.message); } finally { $("analyze").disabled = false; $("analyze").textContent = "分析当前岗位"; } }
async function parseResume() { try { if (!uploadedImages.length) throw new Error("请先选择简历图片。"); $("parseResume").disabled = true; $("parseResume").textContent = "正在提取简历内容…"; const content = [{ type: "text", text: "请读取以下简历图片，完整提取简历中明确出现的全部文字内容。输出标题必须是“简历内容”。只提取原文，不得推测、概括、评价、改写或补充；完整保留个人信息、项目经历、工作经历、岗位名称、公司名称、时间、职责、行动、成果、能力、工具、行业经验、教育经历和其他文字，重点保留简历中提到的项目经理经历、项目管理能力、业务能力、协作能力、专业能力和量化成果。看不清的文字标记为“图片文字不清”，不要猜测。使用清晰的 Markdown 结构，但不要改变原文含义。只输出“简历内容”和提取结果，不要输出候选人画像、分析、评价或建议。" }, ...uploadedImages.map(image => ({ type: "image_url", image_url: { url: image.dataUrl } }))]; const profile = await ai([{ role: "user", content }], 5000); $("candidateProfile").value = profile; await persistConfig(false); toast("简历内容已提取，请检查并保存"); } catch (error) { toast(error.message); } finally { $("parseResume").disabled = false; $("parseResume").textContent = "解析简历图片"; } }
async function sendJob() { try { if (!currentJob) throw new Error("请先分析当前岗位。"); const greeting = $("greeting").value.trim(); if (!greeting) throw new Error("请先生成或填写招呼语。"); const sourceTab = await activeTab(); if (!sourceTab?.url) throw new Error("未找到当前岗位页。"); const shouldSendResume = config.sendResume !== false; let result = await messagePage(sourceTab, { type: "OPEN_COMMUNICATION" }); if (!result?.ok) throw new Error(result?.error || "无法打开 BOSS 沟通页"); toast("正在进入当前岗位沟通页…"); await new Promise(resolve => setTimeout(resolve, 2200)); const sourceAfterClick = await chrome.tabs.get(sourceTab.id); const chatTabs = await chrome.tabs.query({ url: ["*://*.zhipin.com/web/geek/chat*"] }); const chatTab = sourceAfterClick.url?.includes("/web/geek/chat") ? sourceAfterClick : chatTabs.sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0))[0]; if (!chatTab) throw new Error("未进入 BOSS 沟通页，已停止发送。"); result = await messagePage(chatTab, { type: "SEND_MESSAGE", greeting, images: shouldSendResume ? uploadedImages : [], sendResume: shouldSendResume }); if (!result?.ok) throw new Error(result?.error || "发送失败"); const record = { ...currentJob, greeting, status: "已沟通", sentAt: new Date().toLocaleString("zh-CN"), resumeStatus: result.resume?.sent ? "简历图片已确认送达" : (result.resume?.reason || "未发送") }; await send({ type: "SAVE_JOB", job: record }); if (chatTab.id === sourceTab.id) await chrome.tabs.goBack(sourceTab.id); else await chrome.tabs.remove(chatTab.id); toast(result.resume?.sent ? "招呼语和简历图片均已确认送达，已恢复原岗位页" : "招呼语已确认送达并恢复原岗位页"); loadLibrary(); } catch (error) { toast(error.message); } }
async function loadLibrary() { const response = await send({ type: "LIBRARY_GET" }); const jobLibrary = response?.jobLibrary || []; $("libraryList").innerHTML = jobLibrary.length ? jobLibrary.map(job => `<article class="library-item"><h3>${escapeHtml(job.title)}</h3><p>${escapeHtml([job.company, job.location, job.sentAt, job.status].filter(Boolean).join(" · "))}</p></article>`).join("") : `<div class="guide-card"><b>还没有投递记录</b><span>成功发送后，岗位会自动保存在这里。</span></div>`; }
let selectedQueueKeys = new Set();
async function loadQueue() {
  const response = await send({ type: "QUEUE_GET" });
  const queue = response?.queue || [];
  selectedQueueKeys = new Set([...selectedQueueKeys].filter(key => queue.some(item => item.key === key)));
  const batch = response?.batch || { current: 0, total: 0 };
  const batchText = response?.running && batch.total ? `正在投递第 ${batch.current || 1}/${batch.total} 个岗位` : "";
  $("queueProgress").textContent = batchText;
  $("queueList").innerHTML = queue.length ? queue.map(item => {
    const key = encodeURIComponent(item.key);
    const meta = escapeHtml([item.company, item.location, item.status, item.progress, item.error].filter(Boolean).join(" · "));
    const diagnostics = item.rawAiResponse ? `<details class="queue-diagnostic"><summary>查看 AI 原始返回</summary><p class="hint">这是本次批量生成收到的完整返回（最多保留 20,000 个字符），可复制后发给我排查。</p><textarea class="queue-raw-response" rows="12" readonly>${escapeHtml(item.rawAiResponse)}</textarea></details>` : "";
    const details = `<div class="queue-details"><p><b>薪资：</b>${escapeHtml(item.salary || "未读取")}</p><p><b>岗位描述：</b></p><div class="queue-jd">${escapeHtml(item.description || "未读取")}</div>${item.detailUrl ? `<p><a class="queue-link" href="${escapeHtml(item.detailUrl)}" target="_blank">在 BOSS 打开岗位详情</a></p>` : ""}${item.greeting ? `<p><b>打招呼语：</b></p><textarea class="queue-greeting" data-key="${key}" rows="5">${escapeHtml(item.greeting)}</textarea><div class="row"><button class="secondary queue-save" data-key="${key}" ${response?.running ? "disabled" : ""}>保存修改</button></div>` : `<p>招呼语尚未生成，请先点击“批量生成招呼语”。</p>`}${diagnostics}</div>`;
    return `<details class="library-item queue-item"><summary><input class="queue-select" type="checkbox" data-key="${key}" ${selectedQueueKeys.has(item.key) ? "checked" : ""} ${response?.running ? "disabled" : ""} aria-label="选择 ${escapeHtml(item.title)}"><div class="queue-summary-content"><h3>${escapeHtml(item.title)} <span aria-hidden="true">⌄</span></h3><p>${meta}</p></div><button class="queue-delete" type="button" data-key="${key}" ${response?.running ? "disabled" : ""}>删除</button></summary>${details}</details>`;
  }).join("") : `<div class="guide-card"><b>清单为空</b><span>浏览岗位时点击“加入投递清单”。</span></div>`;
  document.querySelectorAll(".queue-save").forEach(button => button.onclick = async () => {
    try {
      const key = decodeURIComponent(button.dataset.key);
      const greeting = document.querySelector(`.queue-greeting[data-key="${button.dataset.key}"]`).value.trim();
      if (!greeting) throw new Error("招呼语不能为空。");
      button.disabled = true; button.textContent = "正在保存…";
      const result = await send({ type: "QUEUE_UPDATE", key, patch: { greeting, status: "待投递", error: "", progress: "等待开始批量投递" } });
      if (!result?.ok) throw new Error(result?.error || "保存失败");
      toast("招呼语已保存，已加入待投递队列"); await loadQueue();
    } catch (error) { toast(`保存失败：${error.message}`); button.disabled = false; button.textContent = "保存修改"; }
  });
  document.querySelectorAll(".queue-select").forEach(input => {
    input.onclick = event => event.stopPropagation();
    input.onchange = () => { const key = decodeURIComponent(input.dataset.key); if (input.checked) selectedQueueKeys.add(key); else selectedQueueKeys.delete(key); $("removeSelected").textContent = `移除所选（${selectedQueueKeys.size}）`; };
  });
  document.querySelectorAll(".queue-delete").forEach(button => button.onclick = async event => {
    event.preventDefault(); event.stopPropagation();
    try {
      const key = decodeURIComponent(button.dataset.key);
      button.disabled = true; button.textContent = "删除中…";
      const result = await send({ type: "QUEUE_REMOVE", key });
      if (!result?.ok) throw new Error("岗位可能已被移除，请刷新清单。");
      selectedQueueKeys.delete(key); toast("已删除 1 个岗位"); await loadQueue();
    } catch (error) { toast(`删除失败：${error.message}`); await loadQueue().catch(() => {}); }
  });
  $("removeSelected").textContent = `移除所选（${selectedQueueKeys.size}）`;
  $("removeSelected").disabled = response?.running || !selectedQueueKeys.size;
  $("selectAll").textContent = queue.length && selectedQueueKeys.size === queue.length ? "取消全选" : "全选";
  $("selectAll").disabled = response?.running || !queue.length;
  const readyCount = queue.filter(item => ["待投递", "待确认"].includes(item.status)).length;
  $("startQueue").textContent = response?.running ? (batch.total ? `正在投递（${batch.current || 1}/${batch.total}）` : "正在投递，请查看岗位状态…") : `开始投递（${readyCount}）`;
  $("startQueue").disabled = !!response?.running;
  return response;
}
async function addCurrentToQueue() { try { const job = await extractJob(); currentJob = job; renderJob(job); const response = await send({ type: "QUEUE_ADD", job }); if (!response?.ok) throw new Error(response?.error || "加入清单失败"); toast("已加入投递清单，当前岗位信息已刷新"); loadQueue(); } catch (error) { toast(error.message); } }
async function removeSelectedQueue() { const button = $("removeSelected"); try { const keys = [...selectedQueueKeys]; if (!keys.length) throw new Error("请先勾选要移出的岗位。"); button.disabled = true; button.textContent = "正在移除…"; const result = await send({ type: "QUEUE_REMOVE_MANY", keys }); const removedCount = Number(result?.removedCount || 0); if (!result?.ok || removedCount !== keys.length) throw new Error(`实际移出 ${removedCount}/${keys.length} 个岗位，请刷新后重试。`); selectedQueueKeys.clear(); toast(`已移出 ${removedCount} 个岗位`); await loadQueue(); } catch (error) { toast(`移除失败：${error.message}`); await loadQueue().catch(() => {}); } }
async function toggleSelectAll() { try { const response = await send({ type: "QUEUE_GET" }); const queue = response?.queue || []; if (!queue.length) return; if (selectedQueueKeys.size === queue.length) { selectedQueueKeys.clear(); toast("已取消全选"); } else { selectedQueueKeys = new Set(queue.map(item => item.key)); toast(`已全选 ${queue.length} 个岗位`); } await loadQueue(); } catch (error) { toast(`全选失败：${error.message}`); } }
let queuePollTimer = null; let queueWasRunning = false;
function startQueuePolling() { clearInterval(queuePollTimer); queuePollTimer = setInterval(async () => { try { const state = await loadQueue(); if (queueWasRunning && !state?.running) { clearInterval(queuePollTimer); queuePollTimer = null; toast("本轮投递已结束，请查看每个岗位的成功或失败状态。"); } queueWasRunning = !!state?.running; } catch (error) { clearInterval(queuePollTimer); queuePollTimer = null; toast(`无法刷新投递状态：${error.message}`); } }, 1000); }
async function generateQueue() { const button = $("generateQueue"); const originalText = button.textContent; try { if (!config.candidateProfile) throw new Error("请先在设置中粘贴或解析简历内容。"); const response = await send({ type: "QUEUE_GET" }); const items = (response?.queue || []).filter(item => !["投递中", "已成功"].includes(item.status)); if (!items.length) throw new Error("清单中没有可生成的岗位。"); button.disabled = true; let success = 0; const failures = []; for (let index = 0; index < items.length; index++) { const item = items[index]; button.textContent = `正在生成 ${index + 1}/${items.length}`; await send({ type: "QUEUE_UPDATE", key: item.key, patch: { status: "生成中", progress: `正在生成第 ${index + 1}/${items.length} 条`, error: "", rawAiResponse: "" } }); await loadQueue(); try { const prompt = buildBatchGreetingPrompt(config.greetingPrompt || DEFAULT_GREETING_PROMPT, config.candidateProfile, item); const data = await parseAiJson(await ai([{ role: "user", content: prompt }], 1600, true)); const greeting = data.greetings?.[0]?.text || data.greeting || ""; if (!greeting) throw new Error("AI 没有返回招呼语"); const saved = await send({ type: "QUEUE_UPDATE", key: item.key, patch: { greeting, status: "待投递", progress: "已生成，等待开始批量投递", error: "", rawAiResponse: "" } }); if (!saved?.ok) throw new Error(saved?.error || "保存生成结果失败"); success++; } catch (error) { failures.push(item.title); await send({ type: "QUEUE_UPDATE", key: item.key, patch: { status: "生成失败", progress: "", error: error.message || String(error), rawAiResponse: error.rawResponse || "" } }); } await loadQueue(); } toast(failures.length ? `已生成 ${success} 条；${failures.length} 条失败，可展开岗位查看 AI 原始返回后重试。` : `已生成 ${success} 条招呼语，现在可直接点击“开始投递”。`); } catch (error) { toast(`批量生成未开始：${error.message}`); } finally { button.disabled = false; button.textContent = originalText; await loadQueue().catch(() => {}); } }
async function startQueue() { const button = $("startQueue"); const originalText = button.textContent; try { const before = await send({ type: "QUEUE_GET" }); if (before?.running) { queueWasRunning = true; button.disabled = true; button.textContent = "正在投递，请查看岗位状态…"; await loadQueue(); startQueuePolling(); toast("投递正在进行中，已开始刷新每个岗位的实时进度。"); return; } const count = (before?.queue || []).filter(item => ["待投递", "待确认"].includes(item.status)).length; if (!count) throw new Error("还没有生成成功的岗位。请先点击“批量生成招呼语”。"); button.disabled = true; button.textContent = `正在启动 ${count} 个岗位…`; toast(`正在启动 ${count} 个岗位的投递，请留在此页面查看状态。`); const response = await send({ type: "QUEUE_START" }); if (!response?.ok) throw new Error(response?.error || "无法开始投递"); queueWasRunning = true; await loadQueue(); startQueuePolling(); toast(response.alreadyRunning ? "投递正在进行中，已开始刷新实时进度。" : `投递已开始：共 ${response.count || count} 个岗位，状态会自动刷新。`); } catch (error) { toast(`未开始投递：${error.message}`); button.disabled = false; button.textContent = originalText; await loadQueue().catch(() => {}); } }
async function loadImages(files) { const next = []; for (const file of files) { if (file.size > 4 * 1024 * 1024) throw new Error(`${file.name} 超过 4MB，请压缩后上传。`); next.push(await new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type, dataUrl: reader.result }); reader.readAsDataURL(file); })); } uploadedImages = next; renderSavedResumes(); await persistConfig(false); toast(`已保存 ${next.length} 张简历图片`); }
document.addEventListener("DOMContentLoaded", async () => { $("version").textContent = `v${chrome.runtime.getManifest().version}`; const stored = await chrome.storage.local.get("config"); const storedConfig = stored.config || {}; config = { endpoint: "https://api.openai.com/v1", model: "gpt-4.1-mini", apiKey: "", candidateProfile: "", greetingPrompt: DEFAULT_GREETING_PROMPT, resumeImages: [], sendResume: true, ...storedConfig }; if (!storedConfig.greetingPrompt || storedConfig.greetingPrompt === LEGACY_GREETING_PROMPT || config.greetingPrompt.includes("{{候选人资料}}")) config.greetingPrompt = DEFAULT_GREETING_PROMPT; uploadedImages = config.resumeImages || []; setupConfig(); renderSavedResumes(); loadLibrary(); document.querySelectorAll(".tab").forEach(button => button.addEventListener("click", () => { document.querySelectorAll(".tab,.page").forEach(el => el.classList.remove("active")); button.classList.add("active"); $(button.dataset.tab).classList.add("active"); })); $("guide").onclick = () => chrome.tabs.create({ url: chrome.runtime.getURL("guide.html") }); $("saveConfig").onclick = () => persistConfig(); $("saveGreetingPrompt").onclick = () => persistConfig(); $("saveProfile").onclick = () => persistConfig(); $("resetGreetingPrompt").onclick = () => { $("greetingPrompt").value = DEFAULT_GREETING_PROMPT; toast("已恢复新的 JD 匹配写作要求，请点击保存写作要求"); }; $("testApi").onclick = async () => { const button = $("testApi"); button.disabled = true; button.textContent = "正在连接…"; try { await allowApiOrigin(); await persistConfig(false); await ai([{ role: "user", content: "只回复：连接成功" }], 20); toast("AI 连接成功"); } catch (error) { toast(error.message); } finally { button.disabled = false; button.textContent = "测试连接"; } }; $("resumeInput").onchange = event => loadImages(event.target.files).catch(error => toast(error.message)); $("parseResume").onclick = parseResume; $("analyze").onclick = analyze; $("refreshGreeting").onclick = analyze; $("send").onclick = sendJob; $("export").onclick = async () => { const response = await send({ type: "EXPORT_JOBS" }); toast(response?.ok ? "已生成 Excel 兼容 CSV" : "导出失败"); }; });
document.addEventListener("DOMContentLoaded", () => { $("addQueueTop").onclick = addCurrentToQueue; $("generateQueue").onclick = generateQueue; $("selectAll").onclick = toggleSelectAll; $("removeSelected").onclick = removeSelectedQueue; $("startQueue").onclick = startQueue; loadQueue(); });
document.addEventListener("DOMContentLoaded", () => { $("sendResume").onchange = async () => { config = { ...config, sendResume: $("sendResume").checked }; await chrome.storage.local.set({ config }); toast(config.sendResume ? "已开启发送简历图片" : "已关闭发送简历图片，本次投递只发送招呼语"); }; });
